version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-deps-{{ .Branch }}-
            - v2-deps-

      - run:
          name: Install npm packages
          command: npm ci

      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Run linting
          command: npm run lint
      - run:
          name: Run unit tests
          command: npm test

  deploy:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - run:
          name: release
          command: npm run semantic-release || true

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
